from connexion.exceptions import OAuthProblem

def verify_token(token):
    return {
        'scope': [],
    }
